**Scatter and Line Graph Plot, Boxplot, Finding Outliers, Outlier Value Table, Quartile Maths, Smoothing, SIRD Model**

In [1]:
#importing python libraries
from google.colab import drive # library used for mounting the Google Drive to Google Colab
import numpy as np # numpy library used for mathematical operations on arrays such as trigonometric, statistical, and algebraic routines
import pandas as pd # pandas library used for data cleaning and analysis
import plotly.graph_objects as go # library used for modified boxplot
import math # math library used for math function

In [2]:
drive.mount('/content/drive') #for mounting the Google Drive to Google Colab

Mounted at /content/drive


In [3]:
dataset1 = pd.read_excel("/content/drive/My Drive/CSE 499/Dataset (Covid-19 in Bangladesh) 15May21 - 11Sept21.xlsx") #read excel file from drive
dataset2 = pd.read_excel("/content/drive/My Drive/CSE 499/Dataset (Covid-19 in Bangladesh) 12Sept21 - 9Jan22.xlsx") #read excel file from drive
dataset3 = pd.read_excel("/content/drive/My Drive/CSE 499/Dataset (Covid-19 in Bangladesh) 10Jan22 - 15May22.xlsx") #read excel file from drive

**Identifying Outliers of Infections**

In [4]:
first120days = dataset1['Infected (Last 24 Hours)']

fig1 = go.Figure()

fig1.add_trace(go.Box(x=first120days, name='',
                marker_color = 'indianred'))

fig1.update_layout(
    xaxis=dict(title='Values from 15May21 - 11Sept21')
)

In [5]:
second120days = dataset2['Infected (Last 24 Hours)']

fig2 = go.Figure()

fig2.add_trace(go.Box(x=second120days, name='',
                marker_color = 'indianred'))

fig2.update_layout(
    xaxis=dict(title='Values from 12Sept21 - 9Jan22')
)

In [6]:
third126days = dataset3['Infected (Last 24 Hours)']

fig3 = go.Figure()

fig3.add_trace(go.Box(x=third126days, name='',
                marker_color = 'indianred'))

fig3.update_layout(
    xaxis=dict(title='Values from 10Jan22 - 15May22')
)

**24 outliers found**

In [7]:
print(np.where(dataset2['Infected (Last 24 Hours)']>1233)) #print outlier values Infected (Last 24 Hours) greater than 1233
print(np.where(dataset3['Infected (Last 24 Hours)']>10888)) #print outlier values Infected (Last 24 Hours) greater than 1233

(array([  0,   1,   2,   3,   4,   5,   7,   8,   9,  10,  16, 119]),)
(array([11, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24]),)


**12 Outliers are above 1233 and correspond date is shown on the y axis**

In [8]:
limit = 1233 # maximum limit of boxplot
date_column = dataset2['Reporting Date'] # assign Reporting Date column from dataset into date_column variable
inf_column = dataset2['Infected (Last 24 Hours)'] # assign Infected (Last 24 Hours) column from dataset into inf_column variable
count_outlier_values = inf_column[inf_column > limit].count() # count the total number of outlier values of Infected (Last 24 Hours)
inf_outlier_date = date_column[inf_column > limit] # find infected outlier reporting date whose limit is greater than 11500 
inf_outlier_values = inf_column[inf_column > limit] # find infected outlier values whose limit is greater than 11500 

print('Total Outlier Values of Infection from 12Sept21 - 9Jan22:', count_outlier_values) # print the total number of outlier values of Infected (Last 24 Hours)
print('\nReporting Date      | Value') # print heading
print('-----------------------------') # print broken line
table_output = "\n".join("{} | {}".format(x, y) for x, y in zip(inf_outlier_date, inf_outlier_values)) # joining table
print(table_output) # print table output of outlier values of Infected (Last 24 Hours) after joining 

Total Outlier Values of Infection from 12Sept21 - 9Jan22: 12

Reporting Date      | Value
-----------------------------
2021-09-12 00:00:00 | 1871
2021-09-13 00:00:00 | 1953
2021-09-14 00:00:00 | 2074
2021-09-15 00:00:00 | 1901
2021-09-16 00:00:00 | 1862
2021-09-17 00:00:00 | 1907
2021-09-19 00:00:00 | 1383
2021-09-20 00:00:00 | 1555
2021-09-21 00:00:00 | 1562
2021-09-22 00:00:00 | 1376
2021-09-28 00:00:00 | 1310
2022-01-09 00:00:00 | 1491


**12 Outliers are above 10888 and correspond date is shown on the y axis**



In [9]:
limit = 10888 # maximum limit of boxplot
date_column = dataset3['Reporting Date'] # assign Reporting Date column from dataset into date_column variable
inf_column = dataset3['Infected (Last 24 Hours)'] # assign Infected (Last 24 Hours) column from dataset into inf_column variable
count_outlier_values = inf_column[inf_column > limit].count() # count the total number of outlier values of Infected (Last 24 Hours)
inf_outlier_date = date_column[inf_column > limit] # find infected outlier reporting date whose limit is greater than 11500 
inf_outlier_values = inf_column[inf_column > limit] # find infected outlier values whose limit is greater than 11500 

print('Total Outlier Values of Infection from from 10Jan22 - 15May22:', count_outlier_values) # print the total number of outlier values of Infected (Last 24 Hours)
print('\nReporting Date      | Value') # print heading
print('-----------------------------') # print broken line
table_output = "\n".join("{} | {}".format(x, y) for x, y in zip(inf_outlier_date, inf_outlier_values)) # joining table
print(table_output) # print table output of outlier values of Infected (Last 24 Hours) after joining 

Total Outlier Values of Infection from from 10Jan22 - 15May22: 12

Reporting Date      | Value
-----------------------------
2022-01-21 00:00:00 | 11434
2022-01-23 00:00:00 | 10906
2022-01-24 00:00:00 | 14828
2022-01-25 00:00:00 | 16033
2022-01-26 00:00:00 | 15527
2022-01-27 00:00:00 | 15807
2022-01-28 00:00:00 | 15440
2022-01-30 00:00:00 | 12183
2022-01-31 00:00:00 | 13501
2022-02-01 00:00:00 | 13154
2022-02-02 00:00:00 | 12193
2022-02-03 00:00:00 | 11596


**First Quartile(Q1), Median, Third Quartile(Q3), Interquartile Range(IQR),Maximum & Minimum of Infection**

In [10]:
minimum = min(dataset1['Infected (Last 24 Hours)']) # formula to find minimum value of Deaths
q1 = dataset1['Infected (Last 24 Hours)'].quantile(0.25) #percentile25(1st quartile of Deaths)
q3 = dataset1['Infected (Last 24 Hours)'].quantile(0.75) #percentile75(3rd quartile of Deaths)
iqr = q3 - q1 #formula of interquartile range of Deaths
lower_limit = (q1 - (1.5 * iqr)) # formula of lower limit of Deaths
upper_limit = (q3 + (1.5 * iqr)) # formula of upper limit of Deaths
maximum = max(dataset1['Infected (Last 24 Hours)']) # formula to find maximum value of Deaths

print('Lower Limit: ',lower_limit) # print lower limit of Deaths
print('Minimum Value: ',minimum) # print minimum value of Deaths
print('First Quartile(Q1): ',q1) #print 1st quartile of Deaths
print('Third Quartile(Q3): ',q3) #print 3rd quartile of Deaths
print('Upper Limit: ',upper_limit) # print upper limit of Deaths
print('Maximum: ',maximum) # print maximum value of Deaths
print('Interquartile Range(IQR): ',iqr) #print interquartile range of Deaths 

Lower Limit:  -8920.5
Minimum Value:  261
First Quartile(Q1):  2434.5
Third Quartile(Q3):  10004.5
Upper Limit:  21359.5
Maximum:  16230
Interquartile Range(IQR):  7570.0


In [11]:
minimum = min(dataset2['Infected (Last 24 Hours)']) # formula to find minimum value of Deaths
q1 = dataset2['Infected (Last 24 Hours)'].quantile(0.25) #percentile25(1st quartile of Deaths)
m = dataset2['Infected (Last 24 Hours)'].quantile(0.50) #percentile50(median of Deaths)
q3 = dataset2['Infected (Last 24 Hours)'].quantile(0.75) #percentile75(3rd quartile of Deaths)
iqr = q3 - q1 #formula of interquartile range of Deaths
lower_limit = (q1 - (1.5 * iqr)) # formula of lower limit of Deaths
upper_limit = (q3 + (1.5 * iqr)) # formula of upper limit of Deaths
maximum = max(dataset2['Infected (Last 24 Hours)']) # formula to find maximum value of Deaths

print('Lower Limit: ',lower_limit) # print lower limit of Deaths
print('Minimum Value: ',minimum) # print minimum value of Deaths
print('First Quartile(Q1): ',q1) #print 1st quartile of Deaths
print('Median: ',m) #print median of Deaths
print('Third Quartile(Q3): ',q3) #print 3rd quartile of Deaths
print('Upper Limit: ',upper_limit) # print upper limit of Deaths
print('Maximum: ',maximum) # print maximum value of Deaths
print('Interquartile Range(IQR): ',iqr) #print interquartile range of Deaths 

Lower Limit:  -389.25
Minimum Value:  0
First Quartile(Q1):  243.75
Median:  309.0
Third Quartile(Q3):  665.75
Upper Limit:  1298.75
Maximum:  2074
Interquartile Range(IQR):  422.0


In [12]:
minimum = min(dataset3['Infected (Last 24 Hours)']) # formula to find minimum value of Deaths
q1 = dataset3['Infected (Last 24 Hours)'].quantile(0.25) #percentile25(1st quartile of Deaths)
q3 = dataset3['Infected (Last 24 Hours)'].quantile(0.75) #percentile75(3rd quartile of Deaths)
iqr = q3 - q1 #formula of interquartile range of Deaths
lower_limit = (q1 - (1.5 * iqr)) # formula of lower limit of Deaths
upper_limit = (q3 + (1.5 * iqr)) # formula of upper limit of Deaths
maximum = max(dataset3['Infected (Last 24 Hours)']) # formula to find maximum value of Deaths

print('Lower Limit: ',lower_limit) # print lower limit of Deaths
print('Minimum Value: ',minimum) # print minimum value of Deaths
print('First Quartile(Q1): ',q1) #print 1st quartile of Deaths
print('Third Quartile(Q3): ',q3) #print 3rd quartile of Deaths
print('Upper Limit: ',upper_limit) # print upper limit of Deaths
print('Maximum: ',maximum) # print maximum value of Deaths
print('Interquartile Range(IQR): ',iqr) #print interquartile range of Deaths 

Lower Limit:  -6304.875
Minimum Value:  4
First Quartile(Q1):  37.5
Third Quartile(Q3):  4265.75
Upper Limit:  10608.125
Maximum:  16033
Interquartile Range(IQR):  4228.25


In [13]:
first120days = dataset1['Deaths (Last 24 Hours)']

fig4 = go.Figure()

fig4.add_trace(go.Box(x=first120days, name='',
                marker_color = 'indianred'))

fig4.update_layout(
    xaxis=dict(title='Values from 15May21 - 11Sept21')
)

In [14]:
second120days = dataset2['Deaths (Last 24 Hours)']

fig5 = go.Figure()

fig5.add_trace(go.Box(x=second120days, name='',
                marker_color = 'indianred'))

fig5.update_layout(
    xaxis=dict(title='Values from 12Sept21 - 9Jan22')
)

In [15]:
third126days = dataset3['Deaths (Last 24 Hours)']

fig6 = go.Figure()

fig6.add_trace(go.Box(x=third126days, name='',
                marker_color = 'indianred'))

fig6.update_layout(
    xaxis=dict(title='Values from 10Jan22 - 15May22')
)

**20 outliers found**

In [16]:
print(np.where(dataset2['Deaths (Last 24 Hours)']>26)) #print outlier values Deaths (Last 24 Hours) greater than 26
print(np.where(dataset3['Deaths (Last 24 Hours)']>31)) #print outlier values Deaths (Last 24 Hours) greater than 31

(array([ 0,  1,  2,  3,  4,  5,  6,  7, 10, 12, 16]),)
(array([20, 23, 24, 26, 28, 29, 30, 31, 36]),)


**11 Outliers are above 26 and correspond date is shown on the y axis**

In [17]:
limit = 26 # maximum limit of boxplot
date_column = dataset2['Reporting Date'] # assign Reporting Date column from dataset into date_column variable
dth_column = dataset2['Deaths (Last 24 Hours)'] # assign Deaths (Last 24 Hours) column from dataset into dth_column variable
count_outlier_values = dth_column[dth_column > limit].count() # count the total number of outlier values of Deaths (Last 24 Hours)
dth_outlier_date = date_column[dth_column > limit] # find deaths outlier reporting date whose limit is greater than 120
dth_outlier_values = dth_column[dth_column > limit] # find deaths outlier values whose limit is greater than 120 

print('Total Outlier Values of Deaths from 12Sept21 - 9Jan22: ', count_outlier_values) # print the total number of outlier values of Deaths (Last 24 Hours)
print('\nReporting Date      | Value') # print heading
print('-----------------------------') # print broken line
table_output1 = "\n".join("{} | {}".format(x, y) for x, y in zip(dth_outlier_date, dth_outlier_values)) # joining table
print(table_output1) # print table output of outlier values of Deaths (Last 24 Hours) after joining 

Total Outlier Values of Deaths from 12Sept21 - 9Jan22:  11

Reporting Date      | Value
-----------------------------
2021-09-12 00:00:00 | 51
2021-09-13 00:00:00 | 41
2021-09-14 00:00:00 | 35
2021-09-15 00:00:00 | 51
2021-09-16 00:00:00 | 51
2021-09-17 00:00:00 | 38
2021-09-18 00:00:00 | 35
2021-09-19 00:00:00 | 43
2021-09-22 00:00:00 | 36
2021-09-24 00:00:00 | 31
2021-09-28 00:00:00 | 31


**9 Outliers are above 31 and correspond date is shown on the y axis**

In [18]:
limit = 31 # maximum limit of boxplot
date_column = dataset3['Reporting Date'] # assign Reporting Date column from dataset into date_column variable
dth_column = dataset3['Deaths (Last 24 Hours)'] # assign Deaths (Last 24 Hours) column from dataset into dth_column variable
count_outlier_values = dth_column[dth_column > limit].count() # count the total number of outlier values of Deaths (Last 24 Hours)
dth_outlier_date = date_column[dth_column > limit] # find deaths outlier reporting date whose limit is greater than 120
dth_outlier_values = dth_column[dth_column > limit] # find deaths outlier values whose limit is greater than 120 

print('Total Outlier Values of Deaths from 10Jan22 - 15May22: ', count_outlier_values) # print the total number of outlier values of Deaths (Last 24 Hours)
print('\nReporting Date      | Value') # print heading
print('-----------------------------') # print broken line
table_output1 = "\n".join("{} | {}".format(x, y) for x, y in zip(dth_outlier_date, dth_outlier_values)) # joining table
print(table_output1) # print table output of outlier values of Deaths (Last 24 Hours) after joining 

Total Outlier Values of Deaths from 10Jan22 - 15May22:  9

Reporting Date      | Value
-----------------------------
2022-01-30 00:00:00 | 34
2022-02-02 00:00:00 | 36
2022-02-03 00:00:00 | 33
2022-02-05 00:00:00 | 36
2022-02-07 00:00:00 | 38
2022-02-08 00:00:00 | 43
2022-02-09 00:00:00 | 33
2022-02-10 00:00:00 | 41
2022-02-15 00:00:00 | 34


**First Quartile(Q1), Median, Third Quartile(Q3), Interquartile Range(IQR),Maximum & Minimum of Deaths**

In [21]:
minimum = min(dataset1['Deaths (Last 24 Hours)']) # formula to find minimum value of Deaths
q1 = dataset1['Deaths (Last 24 Hours)'].quantile(0.25) #percentile25(1st quartile of Deaths)
q3 = dataset1['Deaths (Last 24 Hours)'].quantile(0.75) #percentile75(3rd quartile of Deaths)
iqr = q3 - q1 #formula of interquartile range of Deaths
lower_limit = (q1 - (1.5 * iqr)) # formula of lower limit of Deaths
upper_limit = (q3 + (1.5 * iqr)) # formula of upper limit of Deaths
maximum = max(dataset1['Deaths (Last 24 Hours)']) # formula to find maximum value of Deaths

print('Lower Limit: ',lower_limit) # print lower limit of Deaths
print('Minimum Value: ',minimum) # print minimum value of Deaths
print('First Quartile(Q1): ',q1) #print 1st quartile of Deaths
print('Third Quartile(Q3): ',q3) #print 3rd quartile of Deaths
print('Upper Limit: ',upper_limit) # print upper limit of Deaths
print('Maximum: ',maximum) # print maximum value of Deaths
print('Interquartile Range(IQR): ',iqr) #print interquartile range of Deaths 

Lower Limit:  -183.25
Minimum Value:  17
First Quartile(Q1):  46.25
Third Quartile(Q3):  199.25
Upper Limit:  428.75
Maximum:  264
Interquartile Range(IQR):  153.0


In [19]:
minimum = min(dataset2['Deaths (Last 24 Hours)']) # formula to find minimum value of Deaths
q1 = dataset2['Deaths (Last 24 Hours)'].quantile(0.25) #percentile25(1st quartile of Deaths)
q3 = dataset2['Deaths (Last 24 Hours)'].quantile(0.75) #percentile75(3rd quartile of Deaths)
iqr = q3 - q1 #formula of interquartile range of Deaths
lower_limit = (q1 - (1.5 * iqr)) # formula of lower limit of Deaths
upper_limit = (q3 + (1.5 * iqr)) # formula of upper limit of Deaths
maximum = max(dataset2['Deaths (Last 24 Hours)']) # formula to find maximum value of Deaths

print('Lower Limit: ',lower_limit) # print lower limit of Deaths
print('Minimum Value: ',minimum) # print minimum value of Deaths
print('First Quartile(Q1): ',q1) #print 1st quartile of Deaths
print('Third Quartile(Q3): ',q3) #print 3rd quartile of Deaths
print('Upper Limit: ',upper_limit) # print upper limit of Deaths
print('Maximum: ',maximum) # print maximum value of Deaths
print('Interquartile Range(IQR): ',iqr) #print interquartile range of Deaths 

Lower Limit:  -11.25
Minimum Value:  0
First Quartile(Q1):  3.0
Third Quartile(Q3):  12.5
Upper Limit:  26.75
Maximum:  51
Interquartile Range(IQR):  9.5


In [20]:
minimum = min(dataset3['Deaths (Last 24 Hours)']) # formula to find minimum value of Deaths
q1 = dataset3['Deaths (Last 24 Hours)'].quantile(0.25) #percentile25(1st quartile of Deaths)
q3 = dataset3['Deaths (Last 24 Hours)'].quantile(0.75) #percentile75(3rd quartile of Deaths)
iqr = q3 - q1 #formula of interquartile range of Deaths
lower_limit = (q1 - (1.5 * iqr)) # formula of lower limit of Deaths
upper_limit = (q3 + (1.5 * iqr)) # formula of upper limit of Deaths
maximum = max(dataset3['Deaths (Last 24 Hours)']) # formula to find maximum value of Deaths

print('Lower Limit: ',lower_limit) # print lower limit of Deaths
print('Minimum Value: ',minimum) # print minimum value of Deaths
print('First Quartile(Q1): ',q1) #print 1st quartile of Deaths
print('Third Quartile(Q3): ',q3) #print 3rd quartile of Deaths
print('Upper Limit: ',upper_limit) # print upper limit of Deaths
print('Maximum: ',maximum) # print maximum value of Deaths
print('Interquartile Range(IQR): ',iqr) #print interquartile range of Deaths 

Lower Limit:  -19.125
Minimum Value:  0
First Quartile(Q1):  0.0
Third Quartile(Q3):  12.75
Upper Limit:  31.875
Maximum:  43
Interquartile Range(IQR):  12.75
